fullNameOverride: ""

clusterIssuer:
  shouldInstall: true

cert-manager:
  # This should be enabled and edited for secure clusters such as OpenShift
  # securityContext:
  #   runAsUser: 1000
  installCRDs: true
  image:
    repository: quay.io/jetstack/cert-manager-controller # or edgedelta/jetstack-cert-manager-controller
    tag: "v1.8.0"
  webhook:
    # This should be enabled and edited for secure clusters such as OpenShift
    # securityContext:
    #   runAsUser: 1000
    image:
      repository: quay.io/jetstack/cert-manager-webhook # or edgedelta/jetstack-cert-manager-webhook
      tag: "v1.8.0"
  cainjector:
    # This should be enabled and edited for secure clusters such as OpenShift
    # securityContext:
    #   runAsUser: 1000
    image:
      repository: quay.io/jetstack/cert-manager-cainjector # or edgedelta/jetstack-cert-manager-cainjector
      tag: "v1.8.0"
  startupapicheck:
    # This should be enabled and edited for secure clusters such as OpenShift
    # securityContext:
    #   runAsUser: 1000
    image:
      repository: quay.io/jetstack/cert-manager-ctl # or edgedelta/jetstack-cert-manager-ctl
      tag: "v1.8.0"