{{- if .Values.configtest.handlerOptions.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-test-handler
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: config-test-handler
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.configtest.handlerOptions.replicaCount }}
  selector:
    matchLabels:
      k8s-app: config-test-handler
  template:
    metadata:
      labels:
        k8s-app: config-test-handler
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      {{- if .Values.configtest.handlerOptions.useServiceAccount }}
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.configtest.handlerOptions.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.configtest.handlerOptions.podSecurityContext | nindent 8 }}
      {{- else if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: config-test-handler
        image: {{ .Values.repository }}/function:{{ .Chart.AppVersion }}
        ports:
          - containerPort: {{ .Values.configtest.handlerOptions.port | default 8080 }}
        command:
          - /edgedelta/faas
        env:
          - name: ED_MODE
            value: {{ .Values.configtest.mode | default "prod" | quote }}
          - name: ED_HANDLER_NAME
            value: "configtest"
          - name: ED_REMOTE_REPOSITORY
            value: "1"
          {{- if or .Values.database.dynamodb.enabled .Values.database.scylladb.enabled }} # full on-prem case
          - name: ED_ON_PREM_DYNAMO_ENDPOINT
            {{- if .Values.database.scylladb.enabled }}
            value: http://scylladb-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8000
            {{- else if .Values.database.dynamodb.enabled }}
            value: http://dynamodb-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8000
            {{- end }}
          - name: ED_REMOTE_REPOSITORY_MODE
            value: "full-on-prem"
          - name: ED_DATABASE_TABLE_NAME_PREFIX
            value: "ed"
          - name: ED_ON_PREM_DYNAMO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: {{ .Values.initializer.accessKeyIdName | default "ed-database-access-key-id" | quote }}
                name: {{ .Values.initializer.accessKeyIdName | default "ed-database-access-key-id" | quote }}
          - name: ED_ON_PREM_DYNAMO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: {{ .Values.initializer.secretKeyName | default "ed-database-secret-key" | quote }}
                name: {{ .Values.initializer.secretKeyName | default "ed-database-secret-key" | quote }}
          {{- else }} # hybrid on-prem case
          - name: ED_REMOTE_REPOSITORY_MODE
            value: "hybrid-on-prem"
          - name: ED_REMOTE_TOKEN_FILE
            value: "/etc/{{ .Values.api.tokenSecretName | default "ed-api-token" }}/{{ .Values.api.tokenSecretName | default "ed-api-token" }}"
          - name: ED_API_ENDPOINT
            value: {{ .Values.configtest.apiEndpoint | quote }}
          {{- end }}
          - name: ED_MAX_INFLIGHT
            value: "1"
          - name: STORE_PORT
            value: "8085"
          - name: GODEBUG
            value: "madvdontneed=1"
        resources:
          limits:
            cpu: {{ .Values.configtest.handlerOptions.cpuLimit | default "200m" }}
            memory: {{ .Values.configtest.memoryLimit | default 1 }}Gi
          requests:
            cpu: {{ .Values.configtest.handlerOptions.cpuRequest | default "100m" }}
            memory: {{ .Values.configtest.memoryLimit | default 1 }}Gi
        imagePullPolicy: Always
      {{- if and (not .Values.database.dynamodb.enabled) (not .Values.database.scylladb.enabled) }}
        volumeMounts:
        - name: ed-api-token
          mountPath: "/etc/{{ .Values.api.tokenSecretName | default "ed-api-token" }}"
          readOnly: true
      volumes:
      - name: ed-api-token
        secret:
          secretName: {{ .Values.api.tokenSecretName | default "ed-api-token" | quote }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: config-test-handler-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.configtest.handlerOptions.port | default 8080 }}
  selector:
    k8s-app: config-test-handler
{{- end }}