{{- if .Values.configtest.handlerOptions.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-test-handler
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: config-test-handler
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.configtest.handlerOptions.replicaCount }}
  selector:
    matchLabels:
      k8s-app: config-test-handler
  template:
    metadata:
      labels:
        k8s-app: config-test-handler
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      {{- if .Values.configtest.handlerOptions.useServiceAccount }}
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.configtest.handlerOptions.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.configtest.handlerOptions.podSecurityContext | nindent 8 }}
      {{- else if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: config-test-handler
        image: {{ .Values.repository }}/function:{{ .Chart.AppVersion }}
        ports:
          - containerPort: {{ .Values.configtest.handlerOptions.port | default 8080 }}
        command:
          - /edgedelta/faas
        env:
          - name: ED_MODE
            value: {{ .Values.configtest.mode | default "prod" | quote }}
          - name: ED_HANDLER_NAME
            value: "configtest"
          - name: ED_API_ENDPOINT
            value: {{ .Values.configtest.apiEndpoint | quote }}
          - name: ED_REMOTE_REPOSITORY
            value: "1"
          - name: ED_REMOTE_REPOSITORY_MODE
            value: "hybrid-on-prem"
          - name: ED_REMOTE_TOKEN
            valueFrom:
              secretKeyRef:
                key: {{ .Values.configtest.tokenSecretName | default "ed-api-token" | quote }}
                name: {{ .Values.configtest.tokenSecretName | default "ed-api-token" | quote }}
          - name: ED_MAX_INFLIGHT
            value: "1"
          - name: STORE_PORT
            value: "8085"
          - name: GODEBUG
            value: "madvdontneed=1"
        resources:
          limits:
            cpu: {{ .Values.configtest.handlerOptions.cpuLimit | default "200m" }}
            memory: {{ .Values.configtest.memoryLimit | default 1 }}Gi
          requests:
            cpu: {{ .Values.configtest.handlerOptions.cpuRequest | default "100m" }}
            memory: {{ .Values.configtest.memoryLimit | default 1 }}Gi
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: config-test-handler-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.configtest.handlerOptions.port | default 8080 }}
  selector:
    k8s-app: config-test-handler
{{- end }}