{{- if .Values.rehydration.pollerOptions.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rehydration-poller
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: rehydration-poller
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rehydration-poller
  template:
    metadata:
      labels:
        k8s-app: rehydration-poller
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      {{- if .Values.rehydration.pollerOptions.useServiceAccount }}
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.rehydration.pollerOptions.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.rehydration.pollerOptions.podSecurityContext | nindent 8 }}
      {{- else if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: rehydration-poller
        image: {{ .Values.repository }}/functionpoller:{{ .Chart.AppVersion }}
        command:
          - /edgedelta/functionpoller
        env:
          - name: ED_REHYDRATION_POLL_INTERVAL
            value: {{ .Values.rehydration.pollerOptions.pollInterval | default "10s" | quote }}
          - name: ED_ORG_ID
            {{- if .Values.rehydration.orgId }}
            value: {{ .Values.rehydration.orgId | quote }}
            {{- else if .Values.initializer.provisionOrgID }}
            valueFrom:
              secretKeyRef:
                key: "ed-function-org-id" # this is used when function is triggered for an org created in on-prem-initializer(values are hardcoded in tools/on_prem_init/stages.go:52)
                name: "ed-api-token"
            {{- end }}
          {{- if .Values.openFaas.enabled }}
          - name: ED_OPENFAAS_GATEWAY
            value: "http://gateway-external.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8080"
          {{- else }}
          - name: ED_REHYDRATE_DIRECT_ENDPOINT
            value: "http://rehydration-handler-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:{{ .Values.rehydration.handlerOptions.port | default 8080 }}"
          - name: ED_DISABLE_OPENFAAS
            value: "1"
          {{- end }}
          {{- if .Values.rehydration.agentTagsFilter }}
          - name: ED_AGENT_TAGS_FILTER
            value: {{ .Values.rehydration.agentTagsFilter | quote }}
          {{- end }}
          {{- if or .Values.database.dynamodb.enabled .Values.database.scylladb.enabled }} # full on-prem case
          - name: ED_ON_PREM_DYNAMO_ENDPOINT
            {{- if .Values.database.scylladb.enabled }}
            value: http://scylladb-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8000
            {{- else if .Values.database.dynamodb.enabled }}
            value: http://dynamodb-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8000
            {{- end }}
          - name: ED_REMOTE_REPOSITORY_MODE
            value: "full-on-prem"
          - name: ED_DATABASE_TABLE_NAME_PREFIX
            value: "ed"
          - name: ED_ON_PREM_DYNAMO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: {{ .Values.initializer.accessKeyIdName | default "ed-database-access-key-id" | quote }}
                name: {{ .Values.initializer.accessKeyIdName | default "ed-database-access-key-id" | quote }}
          - name: ED_ON_PREM_DYNAMO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: {{ .Values.initializer.secretKeyName | default "ed-database-secret-key" | quote }}
                name: {{ .Values.initializer.secretKeyName | default "ed-database-secret-key" | quote }}
          {{- else }} # hybrid on-prem case
          - name: ED_REMOTE_REPOSITORY_MODE
            value: "hybrid-on-prem"
          - name: ED_REMOTE_TOKEN
            valueFrom:
              secretKeyRef:
                key: {{ .Values.rehydration.tokenSecretName | default "ed-api-token" | quote }}
                name: {{ .Values.rehydration.tokenSecretName | default "ed-api-token" | quote }}
          - name: ED_API_ENDPOINT
            value: {{ .Values.rehydration.apiEndpoint | quote }}
          {{- end }}
        resources:
          {{- toYaml .Values.rehydration.pollerOptions.resources | nindent 10 }}
        imagePullPolicy: Always
{{- end }}