{{- if .Values.rehydration.handlerOptions.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rehydration-handler
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: rehydration-handler
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rehydration.handlerOptions.replicaCount }}
  selector:
    matchLabels:
      k8s-app: rehydration-handler
  template:
    metadata:
      labels:
        k8s-app: rehydration-handler
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      {{- if .Values.rehydration.handlerOptions.useServiceAccount }}
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: rehydration-handler
        image: {{ .Values.repository }}/function:{{ .Chart.AppVersion }}
        ports:
          - containerPort: {{ .Values.rehydration.handlerOptions.port | default 8080 }}
        command:
          - /edgedelta/faas
        env:
          - name: ED_MODE
            value: {{ .Values.rehydration.mode | default "prod" | quote }}
          - name: ED_REHYDRATION_PUSH_BATCH_SIZE
            value: {{ .Values.rehydration.pushBatchSize | default "10000" | quote }}
          - name: ED_HANDLER_NAME
            value: "rehydrate"
          - name: ED_API_ENDPOINT
            value: {{ .Values.rehydration.apiEndpoint | quote }}
          - name: ED_REMOTE_REPOSITORY
            value: "1"
          - name: ED_REMOTE_REPOSITORY_MODE
            value: "hybrid-on-prem"
          - name: ED_REMOTE_TOKEN
            valueFrom:
              secretKeyRef:
                key: {{ .Values.rehydration.tokenSecretName | default "ed-api-token" | quote }}
                name: {{ .Values.rehydration.tokenSecretName | default "ed-api-token" | quote }}
          - name: ED_MAX_INFLIGHT
            value: "1"
          - name: ED_REHYDRATION_BLOCK_TIMEOUT
            value: 5m
          - name: STORE_PORT
            value: "8085"
          - name: GOGC
          {{- if .Values.rehydration.goGC }}
            value: "{{ .Values.rehydration.goGC }}"
          {{- else }}
            value: "20"
          {{- end }}
          - name: GOMEMLIMIT
            value: "{{ div (mul (.Values.rehydration.memoryLimit | default 16) 9) 10 }}GiB" # This value should be less than memory limit of the pod, ideally 90% of the limit
          - name: GODEBUG
            value: "madvdontneed=1"
          {{- if .Values.rehydration.concurrency }}
          - name: ED_REHYDRATION_CONCURRENCY_LIMIT
            value: "{{ .Values.rehydration.concurrency }}"
          {{- end }}
        resources:
          limits:
            cpu: {{ .Values.rehydration.cpuLimit | default "2000m" }}
            memory: {{ .Values.rehydration.memoryLimit | default 16 }}Gi
          requests:
            cpu: {{ .Values.rehydration.cpuRequest | default "1000m" }}
            memory: {{ .Values.rehydration.memoryLimit | default 16 }}Gi
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rehydration-handler-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rehydration.handlerOptions.port | default 8080 }}
  selector:
    k8s-app: rehydration-handler
{{- end }}