{{- if .Values.database.dynamodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: dynamodb
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: dynamodb
  template:
    metadata:
      labels:
        k8s-app: dynamodb
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      {{- if .Values.database.dynamodb.useServiceAccount }}
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: dynamodb
        image: {{ .Values.database.dynamodb.image }}
        ports:
          - containerPort: 8000
        args:
        - "-jar"
        - "/home/dynamodblocal/DynamoDBLocal.jar"
        - "-port"
        - "8000"
        - "-sharedDb"
        - "-dbPath"
        - "/home/dynamodblocal/data/"
        resources:
          {{- toYaml .Values.database.dynamodb.resources | nindent 12 }}
        imagePullPolicy: Always
        volumeMounts:
          - name: dynamodb-data
            mountPath: /home/dynamodblocal/data
      volumes:
        - name: dynamodb-data
          persistentVolumeClaim:
            claimName: dynamodb-data
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: dynamodb
      port: 8000
  selector:
    k8s-app: dynamodb
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamodb-data
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    {{- toYaml .Values.database.dynamodb.storageResources | nindent 4 }}
{{- end }}