{{- if .Values.influxdb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: influxdb
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: influxdb
  serviceName: influxdb-service
  template:
    metadata:
      labels:
        k8s-app: influxdb
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: influxdb-data
      serviceAccountName:  {{ include "edgedelta.onprem.fullname" . | quote }}
      containers:
        - name: influxdb
          image: "{{ .Values.influxdb.image.repository }}:{{ .Values.influxdb.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: influxdb-svc
              containerPort: {{ .Values.influxdb.port | default 8086 }}
              protocol: TCP
          envFrom:
          - secretRef:
              name: {{ include "edgedelta.onprem.fullname" . }}-auth
          env:
            # Automated setup will not run if an existing boltdb file is found at the configured path.
            # This behavior allows for the InfluxDB container to reboot post-setup without encountering "DB is already set up" errors.
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            # The username to set for the system's initial super-user (Required).
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: {{ .Values.influxdb.adminUser.username | default "admin" }}
            # The name to set for the system's initial organization (Required).
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: {{ .Values.influxdb.adminUser.organization | default "ed-default-organization" }}
            # The name to set for the system's initial bucket (Required).
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: {{ .Values.influxdb.adminUser.bucket | default "default-bucket" }}
            # Path to the BoltDB database.
            - name: INFLUXD_BOLT_PATH
              value: {{ .Values.influxdb.persistence.mountPath | default "/var/lib/influxdb2" }}/influxd.bolt
            # Path to persistent storage engine files where InfluxDB stores all Time-Structure Merge Tree (TSM) data on disk.
            - name: INFLUXD_ENGINE_PATH
              value: {{ .Values.influxdb.persistence.mountPath | default "/var/lib/influxdb2"}}
            - name: INFLUXD_HTTP_BIND_ADDRESS
              value: 0.0.0.0:{{ .Values.influxdb.port | default 8086 }}
          livenessProbe:
            httpGet:
              path: "/health"
              port: influxdb-svc
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/health"
              port: influxdb-svc
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
          - name: data
            mountPath: {{ .Values.influxdb.persistence.mountPath | default "/var/lib/influxdb2" }}
            subPath: {{ .Values.influxdb.persistence.subPath | default "" }}
          resources:
            {{ .Values.influxdb.resources | toYaml | nindent 12 | trim }}
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.influxdb.port | default 8086 }}
      protocol: TCP
      targetPort: influxdb-svc
  selector: 
    k8s-app: influxdb
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-data
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
#   annotations:
#     helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    {{- toYaml .Values.influxdb.persistence.storageResources | nindent 4 }}
{{- end }}