{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edgedelta-ingress
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    helm.sh/hook: post-install
    helm.sh/hook-weight: "100"
    helm.sh/hook-delete-policy: hook-failed
spec:
  tls:
  - hosts:
    - {{ .Values.api.hostName | quote }}
    secretName: tls-backend-secret
  - hosts:
    - {{ .Values.app.hostName | quote }}
    secretName: tls-frontend-secret
  - hosts:
    - {{ .Values.influxdb.hostName | quote }}
    secretName: tls-influxdb-secret
  rules:
    - host: {{ .Values.api.hostName | quote }}
      http:
        paths:
          - backend:
              service:
                name: admin-api-service
                port:
                  number: {{ .Values.api.port | default 4444 }}
            path: /
            pathType: Prefix
    - host: {{ .Values.app.hostName | quote }}
      http:
        paths:
          - backend:
              service:
                name: admin-ui-service
                port:
                  number: {{ .Values.app.port | default 5555 }}
            path: /
            pathType: Prefix
    - host: {{ .Values.influxdb.hostName | quote }}
      http:
        paths:
          - backend:
              service:
                name: influxdb-service
                port:
                  number: {{ .Values.influxdb.port | default 8086 }}
            path: /
            pathType: Prefix
{{- end }}