{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: edgedelta-ingress
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed
spec:
  tls:
  - hosts:
    - {{ .Values.api.hostName | quote }}
    secretName: tls-backend-secret
  - hosts:
    - {{ .Values.app.hostName | quote }}
    secretName: tls-frontend-secret
  rules:
    - host: {{ .Values.api.hostName | quote }}
      http:
        paths:
          - backend:
              serviceName: admin-api-service
              servicePort: {{ .Values.api.port | default 4444 }}
            path: /
    - host: {{ .Values.app.hostName | quote }}
      http:
        paths:
          - backend:
              serviceName: admin-ui-service
              servicePort: {{ .Values.app.port | default 5555 }}
            path: /
{{- end }}