{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edgedelta-ingress
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  {{- if and .Values.api.enabled .Values.api.hostName }}
  - hosts:
    - {{ .Values.api.hostName | quote }}
    secretName: tls-backend-secret
  {{- end }}
  {{- if and .Values.app.enabled .Values.app.hostName }}
  - hosts:
    - {{ .Values.app.hostName | quote }}
    secretName: tls-frontend-secret
  {{- end }}
  {{- if and .Values.influxdb.enabled .Values.influxdb.hostName }}
  - hosts:
    - {{ .Values.influxdb.hostName | quote }}
    secretName: tls-influxdb-secret
  {{- end }}
  {{- if and .Values.elasticsearch.enabled .Values.elasticsearch.connection.hostName }}
  - hosts:
    - {{ .Values.elasticsearch.connection.hostName | quote }}
    secretName: tls-elasticsearch-secret
  {{- end }}
  rules:
    {{- if and .Values.api.enabled .Values.api.hostName }}
    - host: {{ .Values.api.hostName | quote }}
      http:
        paths:
          - backend:
              service:
                name: admin-api-service
                port:
                  number: {{ .Values.api.port | default 4444 }}
            path: /
            pathType: Prefix
    {{- end }}
    {{- if and .Values.app.enabled .Values.app.hostName }}
    - host: {{ .Values.app.hostName | quote }}
      http:
        paths:
          - backend:
              service:
                name: admin-ui-service
                port:
                  number: {{ .Values.app.port | default 5555 }}
            path: /
            pathType: Prefix
    {{- end }}
    {{- if and .Values.influxdb.enabled .Values.influxdb.hostName }}
    - host: {{ .Values.influxdb.hostName | quote }}
      http:
        paths:
          - backend:
              service:
                name: influxdb-service
                port:
                  number: {{ .Values.influxdb.port | default 8086 }}
            path: /
            pathType: Prefix
    {{- end }}
    {{- if and .Values.elasticsearch.enabled .Values.elasticsearch.connection.hostName }}
    - host: {{ .Values.elasticsearch.connection.hostName | quote }}
      http:
        paths:
          - backend:
              service:
                name: elasticsearch-service
                port:
                  number: {{ .Values.elasticsearch.connection.port | default 9200 }}
            path: /
            pathType: Prefix
    {{- end }}
{{- end }}