{{- if .Values.clusterIssuer.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: label-ns
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed
spec:
  template:
    spec:
      containers:
      - name: labeler
        image: {{ .Values.clusterIssuer.namespaceLabeler.image }}
        command:
        - kubectl
        - label
        - ns
        - {{ .Release.Namespace }}
        - cert-manager.io/disable-validation=true
      restartPolicy: Never
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
{{- end }}