{{- if .Values.openFaas.proLicense }}
apiVersion: v1
kind: Secret
metadata:
  name: openfaas-license
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: hook-failed
data:
  license: {{ .Values.openFaas.proLicense | b64enc | quote }}
{{- end }}