{{- if .Values.rehydration.pollerOptions.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rehydration-poller
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: rehydration-poller
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rehydration-poller
  template:
    metadata:
      labels:
        k8s-app: rehydration-poller
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      {{- if .Values.rehydration.pollerOptions.useServiceAccount }}
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: rehydration-poller
        image: {{ .Values.repository }}/rehydrationpoller:{{ .Chart.AppVersion }}
        command:
          - /edgedelta/rehydrationpoller
        env:
          - name: ED_REHYDRATION_POLL_INTERVAL
            value: {{ .Values.rehydration.pollerOptions.pollInterval | default "10s" | quote }}
          - name: ED_ORG_ID
            {{- if .Values.rehydration.orgId }}
            value: {{ .Values.rehydration.orgId | quote }}
            {{- else }}
            valueFrom:
              secretKeyRef:
                key: "ed-rehydration-org-id" # this is used when rehydration is triggered for an org created in on-prem-initializer(values are hardcoded in tools/on_prem_init/stages.go:52)
                name: "ed-rehydration-token" 
            {{- end }}
          - name: ED_API_ENDPOINT
            value: {{ .Values.rehydration.apiEndpoint | quote }}
          {{- if .Values.openFaas.enabled }}
          - name: ED_OPENFAAS_GATEWAY
            value: "http://gateway-external.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8080"
          {{- else }}
          - name: ED_REHYDRATE_DIRECT_ENDPOINT
            value: "http://rehydration-handler-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:{{ .Values.rehydration.handlerOptions.port | default 8080 }}"
          - name: ED_DISABLE_OPENFAAS
            value: "1"
          {{- end }}
          - name: ED_REMOTE_TOKEN
            valueFrom:
              secretKeyRef:
                key: {{ .Values.rehydration.tokenSecretName | default "ed-rehydration-token" | quote }}
                name: {{ .Values.rehydration.tokenSecretName | default "ed-rehydration-token" | quote }}
        resources:
          {{- toYaml .Values.rehydration.pollerOptions.resources | nindent 10 }}
        imagePullPolicy: Always
{{- end }}