{{- if .Values.usingOpenShift }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "edgedelta.onprem.fullname" . | quote }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-9"
    helm.sh/hook-delete-policy: before-hook-creation
priority: 999
runAsUser:
  type: MustRunAsRange
  range: 1,10000000001
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1
    max: 10000000001
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- SYS_NICE
defaultAddCapabilities: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "edgedelta.onprem.fullname" . }}
{{- end }}