{{- if .Values.scylla.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylladb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: scylladb
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: scylladb
  template:
    metadata:
      labels:
        k8s-app: scylladb
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: scylladb
        image: {{ .Values.scylla.image }}
        ports:
          - containerPort: 8000
          - containerPort: 9042
        args:
        - --alternator-address=0.0.0.0
        - --alternator-port=8000
        - --alternator-write-isolation=always
        resources:
          {{- toYaml .Values.scylla.resources | nindent 12 }}
        imagePullPolicy: Always
        volumeMounts:
          - name: scylladb-config
            mountPath: /etc/scylla
          - name: scylladb-data
            mountPath: /var/lib/scylla
      volumes:
        - name: scylladb-config
          configMap:
            name: scylladb-config
        - name: scylladb-data
          persistentVolumeClaim:
            claimName: scylladb-data
---
apiVersion: v1
kind: Service
metadata:
  name: scylladb-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: alternator
      port: 8000
    - name: cassandra
      port: 9042
  selector:
    k8s-app: scylladb
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scylladb-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
data:
  scylla.yaml: |
    {{- .Values.scylla.config | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scylladb-data
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    {{- toYaml .Values.scylla.storageResources | nindent 4 }}
{{- end }}