apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
  {{- $name := printf "%s-auth" (include "edgedelta.onprem.fullname" .) }}
  name: {{ $name }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- $previous := lookup "v1" "Secret" .Release.Namespace $name }}
  {{- $scyllaKeyId := .Values.initializer.accessKeyIdName | default "ed-scylladb-access-key-id" }}
  {{- $scyllaKeyName := .Values.initializer.secretKeyName | default "ed-scylladb-secret-key" }}

  {{- if $previous }}
  influx-admin-token: {{ index $previous.data "influx-admin-token" }}
  {{- else }}
  influx-admin-token: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

  {{- if $previous }}
  influx-admin-password: {{ index $previous.data "influx-admin-password" }}
  {{- else }}
  influx-admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

  {{- if $previous }}
  {{ $scyllaKeyId }}: {{ index $previous.data $scyllaKeyId }}
  {{- else }}
  {{ $scyllaKeyId }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

  {{- if $previous }}
  {{ $scyllaKeyName }}: {{ index $previous.data $scyllaKeyName }}
  {{- else }}
  {{ $scyllaKeyName }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}