{{- if and .Values.batchJobs.configValidation.enabled .Values.elasticsearch.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: config-validation
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: batchjob
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.batchJobs.configValidation.cronString | default "0 16 * * *" | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.batchJobs.useServiceAccount }}
          serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
          {{- end }}
          {{- if .Values.batchJobs.podSecurityContext }}
          securityContext:
            {{- toYaml .Values.batchJobs.podSecurityContext | nindent 12 }}
          {{- else if .Values.podSecurityContext }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- end }}
          containers:
          - name: config-validation
            image: {{ .Values.repository }}/batchjob:on-prem-{{ .Chart.AppVersion }}
            env:
              - name: ED_SECRET_PROVIDER
                value: "env"
              - name: ED_TRACE_FILES
                value: "job_manager,span,confvalidation"
              - name: ELASTICSEARCH_ADMIN_USER
                value: elastic
              - name: ED_BACKEND_ON_PREMISE
                value: "1"
              - name: ED_DATABASE_TABLE_NAME_PREFIX
                value: "ed"
              - name: BACKEND_ON_PREMISE_DYNAMO_ENDPOINT
                {{- if .Values.database.scylladb.enabled }}
                value: http://scylladb-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8000
                {{- else if .Values.database.dynamodb.enabled }}
                value: http://dynamodb-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8000
                {{- end }}
              - name: BACKEND_ON_PREMISE_DYNAMO_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: {{ .Values.initializer.accessKeyIdName | default "ed-database-access-key-id" | quote }}
                    name: {{ .Values.initializer.accessKeyIdName | default "ed-database-access-key-id" | quote }}
              - name: BACKEND_ON_PREMISE_DYNAMO_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    key: {{ .Values.initializer.secretKeyName | default "ed-database-secret-key" | quote }}
                    name: {{ .Values.initializer.secretKeyName | default "ed-database-secret-key" | quote }}
            command:
              - /edgedelta/batchjob
            args:
              - --mode
              - prod
              - --job
              - config-validation
              - --no-state
              - --timeout
              - {{ .Values.batchJobs.configValidation.timeout | default "1h" | quote }}
            imagePullPolicy: Always
          restartPolicy: Never
{{- end }}