{{- if and .Values.batchJobs.correlatedSignal.enabled .Values.elasticsearch.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: correlated-signal
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: batchjob
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.batchJobs.correlatedSignal.cronString | default "*/5 * * * *" | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.batchJobs.useServiceAccount }}
          serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
          {{- end }}
          {{- if .Values.batchJobs.podSecurityContext }}
          securityContext:
            {{- toYaml .Values.batchJobs.podSecurityContext | nindent 12 }}
          {{- else if .Values.podSecurityContext }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- end }}
          containers:
          - name: correlated-signal
            image: {{ .Values.repository }}/batchjob:on-prem-{{ .Chart.AppVersion }}
            env:
              - name: ED_SECRET_PROVIDER
                value: "env"
              - name: ELASTICSEARCH_ADMIN_USER
                value: elastic
              - name: ED_TRACE_FILES
                value: "job_manager,span,correlated_signal_evaluator_v2,log_repo"
              - name: ED_BACKEND_ON_PREMISE
                value: "1"
              - name: ED_DATABASE_TABLE_NAME_PREFIX
                value: "ed"
              - name: BACKEND_ON_PREMISE_DYNAMO_ENDPOINT
                {{- if .Values.database.scylladb.enabled }}
                value: http://scylladb-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8000
                {{- else if .Values.database.dynamodb.enabled }}
                value: http://dynamodb-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8000
                {{- end }}
              - name: BACKEND_ON_PREMISE_DYNAMO_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: {{ .Values.initializer.accessKeyIdName | default "ed-database-access-key-id" | quote }}
                    name: {{ .Values.initializer.accessKeyIdName | default "ed-database-access-key-id" | quote }}
              - name: BACKEND_ON_PREMISE_DYNAMO_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    key: {{ .Values.initializer.secretKeyName | default "ed-database-secret-key" | quote }}
                    name: {{ .Values.initializer.secretKeyName | default "ed-database-secret-key" | quote }}
              {{- if .Values.elasticsearch.connection.cloud_id }}
              - name: BACKEND_ON_PREMISE_ELASTIC_CLOUD_ID
                value: {{ .Values.elasticsearch.connection.cloud_id | quote }}
              {{- else }}
              {{- if .Values.elasticsearch.image.enabled }}
              - name: BACKEND_ON_PREMISE_ELASTIC_ADDRESSES
              {{- $eport := .Values.elasticsearch.connection.port | default 9200 }}
              {{- if .Values.elasticsearch.connection.hostName }}
                value: "https://{{ .Values.elasticsearch.connection.hostName }}"
              {{- else }}
                value: "http://elasticsearch-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:{{ $eport }}"
              {{- end }}
              {{- else }}
              - name: BACKEND_ON_PREMISE_ELASTIC_ADDRESSES
                value: {{ .Values.elasticsearch.connection.addresses | quote }}
              {{- end }}
              {{- end }}
              {{- if .Values.elasticsearch.connection.token }}
              - name: BACKEND_ON_PREMISE_ELASTIC_TOKEN
                value: {{ .Values.elasticsearch.connection.token | quote }}
              {{- else }}
              {{- if .Values.elasticsearch.image.enabled }}
              - name: BACKEND_ON_PREMISE_ELASTIC_USERNAME
                value: "elastic" # when image is enabled username is always elastic
              {{- else }}
              - name: BACKEND_ON_PREMISE_ELASTIC_USERNAME
                value: {{ .Values.elasticsearch.connection.username | quote }}
              {{- end }}
              - name: BACKEND_ON_PREMISE_ELASTIC_PASSWORD
                value: {{ .Values.elasticsearch.connection.password | default "elastic-password" | quote }}
              {{- end }}
              {{- if .Values.elasticsearch.connection.region }}
              - name: BACKEND_ON_PREMISE_ELASTIC_REGION
                value: {{ .Values.elasticsearch.connection.region | quote }}
              {{- end }}
            command:
              - /edgedelta/batchjob
            args:
              - --mode
              - prod
              - --job
              - correlated-signal-v2
              - --window
              - {{ .Values.batchJobs.correlatedSignal.window | default "15m" | quote }}
              - --offset
              - {{ .Values.batchJobs.correlatedSignal.offset | default "1m" | quote }}
              - --timeout
              - {{ .Values.batchJobs.correlatedSignal.timeout | default "5m" | quote }}
            imagePullPolicy: Always
          restartPolicy: Never
{{- end }}