{{- if and .Values.batchJobs.crashLoopDetector.enabled (and .Values.elasticsearch.enabled .Values.influxdb.enabled) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: crash-loop-detector
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: batchjob
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.batchJobs.crashLoopDetector.cronString | default "*/5 * * * *" | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crash-loop-detector
            image: {{ .Values.repository }}/batchjob:on-prem-{{ .Chart.AppVersion }}
            {{- if .Values.batchJobs.crashLoopDetector.metricPort }}
            ports:
              - name: metrics
                containerPort: {{ .Values.batchJobs.crashLoopDetector.metricPort }}
            {{- end }}
            env:
              - name: ED_SECRET_PROVIDER
                value: "env"
              - name: ED_TRACE_FILES
                value: "job_manager,crash_loop_detector,span"
              - name: ELASTICSEARCH_ADMIN_USER
                value: elastic
              - name: ED_BACKEND_ON_PREMISE
                value: "1"
              - name: ED_DATABASE_TABLE_NAME_PREFIX
                value: "ed"
              - name: BACKEND_ON_PREMISE_DYNAMO_ENDPOINT
                {{- if .Values.database.scylladb.enabled }}
                value: http://scylladb-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8000
                {{- else if .Values.database.dynamodb.enabled }}
                value: http://dynamodb-service.{{ .Release.Namespace }}.{{ .Values.dnsSuffix }}:8000
                {{- end }}
              - name: BACKEND_ON_PREMISE_DYNAMO_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: {{ .Values.initializer.accessKeyIdName | default "ed-database-access-key-id" | quote }}
                    name: {{ .Values.initializer.accessKeyIdName | default "ed-database-access-key-id" | quote }}
              - name: BACKEND_ON_PREMISE_DYNAMO_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    key: {{ .Values.initializer.secretKeyName | default "ed-database-secret-key" | quote }}
                    name: {{ .Values.initializer.secretKeyName | default "ed-database-secret-key" | quote }}
            command:
              - /edgedelta/batchjob
            args:
              - --mode
              - prod
              - --job
              - crash-loop-detector-v2
              - --window
              - {{ .Values.batchJobs.crashLoopDetector.window | default "5m" | quote }}
              - --offset
              - {{ .Values.batchJobs.crashLoopDetector.offset | default "1m" | quote }}
              - --timeout
              - {{ .Values.batchJobs.crashLoopDetector.timeout | default "10m" | quote }}
            imagePullPolicy: Always
          restartPolicy: Never
{{- end }}