apiVersion: v2
name: on-prem-rehydrations
description: Edge Delta On-Prem Rehydrations Chart for Kubernetes
type: application
version:  0.1.0
appVersion: v0.1.0
dependencies:
  - name: openfaas
    repository: https://openfaas.github.io/faas-netes
    version: 10.0.7
    condition: openFaas.enabled