apiVersion: v2
name: edgedelta-on-prem
description: Edge Delta On-Prem Deployment Chart for Kubernetes
type: application
version:  0.1.4
appVersion: v0.1.4

dependencies:
  - name: openfaas
    repository: https://openfaas.github.io/faas-netes
    version: 10.0.7
    condition: openFaas.enabled
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.1.0
    condition: ingress.shouldInstall
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.8.0
    condition: clusterIssuer.shouldInstall