{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-keeper-config
  namespace: {{ .Release.Namespace | quote }}
data:
  keeper.xml: |
    <?xml version="1.0"?>
    <clickhouse>
        <listen_host>0.0.0.0</listen_host>
        <logger>
            <level>trace</level>
            <console>1</console>
        </logger>
        <openSSL>
            <server>
                <certificateFile remove="1"/>
                <privateKeyFile remove="1"/>
            </server>
        </openSSL>
        <keeper_server>
            <tcp_port>2181</tcp_port>
            <server_id from_env="CK_INDEX"/>
            
            <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <session_timeout_ms>30000</session_timeout_ms>
            </coordination_settings>
            
            <raft_configuration>
                <server>
                    <id>0</id>
                    <hostname>clickhouse-keeper-0.clickhouse-keepers.{{- .Release.Namespace -}}</hostname>
                    <port>9444</port>
                </server>
                <server>
                    <id>1</id>
                    <hostname>clickhouse-keeper-1.clickhouse-keepers.{{- .Release.Namespace -}}</hostname>
                    <port>9444</port>
                </server>
                <server>
                    <id>2</id>
                    <hostname>clickhouse-keeper-2.clickhouse-keepers.{{- .Release.Namespace -}}</hostname>
                    <port>9444</port>
                </server>
            </raft_configuration>
        </keeper_server>
        
        <zookeeper>
            <node>
                <host>clickhouse-keeper-0.clickhouse-keepers.{{- .Release.Namespace -}}</host>
                <port>2181</port>
            </node>
            <node>
                <host>clickhouse-keeper-1.clickhouse-keepers.{{- .Release.Namespace -}}</host>
                <port>2181</port>
            </node>
            <node>
                <host>clickhouse-keeper-2.clickhouse-keepers.{{- .Release.Namespace -}}</host>
                <port>2181</port>
            </node>
        </zookeeper>
    </clickhouse>
  prometheus.xml: |
    <clickhouse>
      <prometheus>
        <endpoint>/metrics</endpoint>
        <port>8001</port>
        <metrics>true</metrics>
        <events>true</events>
        <asynchronous_metrics>true</asynchronous_metrics>
      </prometheus>
    </clickhouse>
---
# Headless
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-keepers
  namespace: {{ .Release.Namespace | quote }}
spec:
  clusterIP: None
  ports:
    - name: rest
      port: 8123
    - name: keeper
      port: 2181
    - name: replica-a
      port: 9000
    - name: replica-b
      port: 9009
    - name: raft
      port: 9444
    - name: metrics
      port: 8001
  selector:
    k8s-app: clickhouse-keeper
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse-keeper
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: clickhouse-keeper
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      k8s-app: clickhouse-keeper
  serviceName: clickhouse-keepers
  replicas: 3
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        k8s-app: clickhouse-keeper
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      {{- if .Values.clickhouse.useServiceAccount }}
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
      {{- end }}
      {{- if .Values.clickhouse.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.clickhouse.podSecurityContext | nindent 8 }}
      {{- else if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: clickhouse
          image: {{ .Values.clickhouse.image }}
          imagePullPolicy: IfNotPresent
          workingDir: /
          command:
            - /bin/bash
            - -c
            - |-
              export CK_INDEX=${HOSTNAME##*-}
              ./entrypoint.sh
          resources:
            {{- toYaml .Values.clickhouse.resources | nindent 12 }}
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: rest
              containerPort: 8123
            - name: keeper
              containerPort: 2181
            - name: replica-a
              containerPort: 9000
            - name: replica-b
              containerPort: 9009
            - name: raft
              containerPort: 9444
          volumeMounts:
            - name: clickhouse-keeper-config
              mountPath: /etc/clickhouse-server/config.d/
      volumes:
        - name: clickhouse-keeper-config
          configMap:
            name: clickhouse-keeper-config
            items:
              - key: keeper.xml
                path: keeper.xml
              - key: prometheus.xml 
                path: prometheus.xml 
{{- end }}