{{- if .Values.clickhouse.enabled }}
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "rh"
  namespace: {{ .Release.Namespace | quote }}

spec:
  defaults:
    templates: 
      podTemplate: pod-template
      serviceTemplate: chi-service-template
 
  configuration:
    files:
      config.d/ed_misc.xml: |
        <clickhouse>
          <max_server_memory_usage>{{- .Values.clickhouse.maxMemoryUsage | int64 -}}</max_server_memory_usage>
          <max_concurrent_queries>500</max_concurrent_queries>
        </clickhouse>
      config.d/ed_system_tables.xml: |
        <clickhouse>
          <query_log replace="1">
            <database>system</database>
            <table>query_log</table>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
            <engine>
              ENGINE = MergeTree
              PARTITION BY toYYYYMM(event_date)
              ORDER BY (event_time)
              TTL toStartOfMonth(event_date) + INTERVAL 1 MONTH
              SETTINGS ttl_only_drop_parts=1
            </engine>
          </query_log>

          <part_log replace="1">
            <database>system</database>
            <table>part_log</table>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
            <engine>
              ENGINE = MergeTree
              PARTITION BY toYYYYMM(event_date)
              ORDER BY (event_time)
              TTL toStartOfMonth(event_date) + INTERVAL 1 MONTH
              SETTINGS ttl_only_drop_parts=1
            </engine>
          </part_log>
        </clickhouse>
    zookeeper:
      nodes:
      - host: clickhouse-keeper-0.clickhouse-keepers.{{- .Release.Namespace }}
        port: 2181
      - host: clickhouse-keeper-1.clickhouse-keepers.{{- .Release.Namespace }}
        port: 2181
      - host: clickhouse-keeper-2.clickhouse-keepers.{{- .Release.Namespace }}
        port: 2181
    clusters:
      - name: default
        layout:
          shardsCount: {{ .Values.clickhouse.shardsCount | default 1 }}
    profiles:
      default/default_database_engine: "Atomic"
      # default/max_threads: 8
      default/max_bytes_before_external_group_by: 8000000000
      default/max_bytes_before_external_sort: 8000000000
    users:
      default/networks/ip: "::/0"

  templates:
    podTemplates:
      - name: pod-template
        spec:
          {{- if .Values.clickhouse.useServiceAccount }}
          serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
          {{- end }}
          {{- if .Values.clickhouse.podSecurityContext }}
          securityContext:
          {{- toYaml .Values.clickhouse.podSecurityContext | nindent 10 }}
          {{- else if .Values.podSecurityContext }}
          securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 10 }}
          {{- end }}
          containers:
            - name: clickhouse-pod
              image: {{ .Values.clickhouse.image }}
              workingDir: /
              command:
                - ./entrypoint.sh
              resources:
                {{- toYaml .Values.clickhouse.resources | nindent 16 }}
    serviceTemplates:
      - name: chi-service-template
        generateName: "{chi}-ch-srv"
        metadata:
        spec:
          selector:
            clickhouse.altinity.com/app: chop
            clickhouse.altinity.com/chi: clickhouse
            clickhouse.altinity.com/cluster: default
          ports:
            - name: ch-srv
              port: 9000
              protocol: TCP
              targetPort: 9000
            - name: ch-srv-http
              port: 8123
              protocol: TCP
              targetPort: 8123
          type: ClusterIP
{{- end }}