{{- if .Values.influxdb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: influxdb
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: influxdb
  serviceName: influxdb-service
  template:
    metadata:
      labels:
        k8s-app: influxdb
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      {{- if .Values.influxdb.useServiceAccount }}
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
      {{- end }}
      {{- if .Values.influxdb.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.influxdb.podSecurityContext | nindent 8 }}
      {{- else if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- else if not .Values.usingOpenShift }}
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      {{- end }}
      containers:
        - name: influxdb
          image: "{{ .Values.influxdb.image.repository }}:{{ .Values.influxdb.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: influxdb-svc
              containerPort: {{ .Values.influxdb.port | default 8086 }}
              protocol: TCP
          envFrom:
          - secretRef:
              name: {{ include "edgedelta.onprem.fullname" . }}-auth
          env:
            # Automated setup will not run if an existing boltdb file is found at the configured path.
            # This behavior allows for the InfluxDB container to reboot post-setup without encountering "DB is already set up" errors.
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            # The username to set for the system's initial super-user (Required).
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: {{ .Values.influxdb.adminUser.username | default "admin" }}
            # The name to set for the system's initial organization (Required).
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: {{ .Values.influxdb.adminUser.organization | default "ed-default-organization" }}
            # The name to set for the system's initial bucket (Required).
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: {{ .Values.influxdb.adminUser.bucket | default "default-bucket" }}
            # Path to the BoltDB database.
            - name: INFLUXD_BOLT_PATH
              value: {{ .Values.influxdb.persistence.mountPath | default "/bitnami/influxdb" }}/influxd.bolt
            # Path to persistent storage engine files where InfluxDB stores all Time-Structure Merge Tree (TSM) data on disk.
            - name: INFLUXD_ENGINE_PATH
              value: {{ .Values.influxdb.persistence.mountPath | default "/bitnami/influxdb"}}
            - name: INFLUXD_HTTP_BIND_ADDRESS
              value: 0.0.0.0:{{ .Values.influxdb.port | default 8086 }}
          livenessProbe:
            httpGet:
              path: "/health"
              port: influxdb-svc
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/health"
              port: influxdb-svc
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
          - name: influxdb-data
            mountPath: {{ .Values.influxdb.persistence.mountPath | default "/bitnami/influxdb" }}
          resources:
            {{ .Values.influxdb.resources | toYaml | nindent 12 | trim }}
  volumeClaimTemplates:
    - metadata:
        name: influxdb-data
      spec:
        {{- if .Values.storageClassName }}
        storageClassName: {{ .Values.storageClassName }}
        {{- end }}
        accessModes:
          - "ReadWriteOnce"
        resources:
          {{- toYaml .Values.influxdb.persistence.storageResources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.influxdb.port | default 8086 }}
      protocol: TCP
      targetPort: influxdb-svc
  selector: 
    k8s-app: influxdb
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
{{- end }}