{{- if .Values.database.scylladb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scylladb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: scylladb
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: scylladb
  serviceName: scylladb-service
  template:
    metadata:
      labels:
        k8s-app: scylladb
        {{- include "edgedelta.onprem.labels" . | nindent 8 }}
    spec:
      {{- if .Values.database.scylladb.useServiceAccount }}
      serviceAccountName: {{ include "edgedelta.onprem.fullname" . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: scylladb
        {{- if .Values.database.scylladb.useNonRoot.enabled }}
        image: {{ .Values.database.scylladb.useNonRoot.image }}
        {{- else }}
        image: {{ .Values.database.scylladb.image }}
        {{- end }}
        {{- if .Values.database.scylladb.useNonRoot.enabled }}
        securityContext:
          capabilities:
            add:
            - SYS_NICE
        {{- end }}
        ports:
          - containerPort: 8000
          - containerPort: 9042
        args:
        - --alternator-address=0.0.0.0
        - --alternator-port=8000
        - --alternator-write-isolation=always
        {{- if .Values.database.scylladb.useDeveloperMode }}
        - --developer-mode=1
        {{- else }}
        - --developer-mode=0
        {{- end }}
        - --overprovisioned=1
        - --smp=$(CPU_COUNT)
        env:
        - name: CPU_COUNT
          valueFrom:
            resourceFieldRef:
              containerName: scylladb
              divisor: "1"
              resource: limits.cpu
        resources:
          {{- toYaml .Values.database.scylladb.resources | nindent 12 }}
        imagePullPolicy: Always
        volumeMounts:
          - name: scylladb-config
            mountPath: /etc/scylla
          - name: scylladb-data
          {{- if .Values.database.scylladb.useNonRoot.enabled }}
            mountPath: /opt/scylladb/scylla/data
          {{- else }}
            mountPath: /var/lib/scylla
          {{- end }}
      volumes:
        - name: scylladb-config
          configMap:
            name: scylladb-config
  volumeClaimTemplates:
    - metadata:
        name: scylladb-data
      spec:
        {{- if .Values.storageClassName }}
        storageClassName: {{ .Values.storageClassName }}
        {{- end }}
        accessModes:
          - "ReadWriteOnce"
        resources:
          {{- toYaml .Values.database.scylladb.storageResources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: scylladb-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: alternator
      port: 8000
    - name: cassandra
      port: 9042
  selector:
    k8s-app: scylladb
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scylladb-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "edgedelta.onprem.labels" . | nindent 4 }}
data:
  scylla.yaml: |
    {{- if .Values.database.scylladb.useNonRoot.enabled }}
    {{- deepCopy (fromYaml .Values.database.scylladb.config) | merge (fromYaml .Values.database.scylladb.nonRootConfigExtras) | toYaml | nindent 4 }}
    {{- else }}
    {{- .Values.database.scylladb.config | nindent 4 }}
    {{- end }}
{{- end }}